name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYYMMDD-HHmmss'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: npm install --frozen-lockfile

      - run: PUBLIC_URL=https://cdn.jsdelivr.net/gh/test-auto-deploy/online-page@${{steps.time.outputs.time}} npm run build
        env:
            CI: false

      - name: Deploy
        run: |
          rm -rf .git
          git clone --depth 1 ${{ secrets.DEPLOY_REPO }} ./dist
          ls -ahl
          cp -rf ./build/* ./dist
          cd ./dist
          git config user.name m-g-
          git config user.email 1121506496@qq.com
          git add .
          #echo "Deploying to production server on branch $GITHUB_REF"
          git commit -m "Deploy tag ${{ steps.time.outputs.time }}"
          git push origin master
          git tag ${{ steps.time.outputs.time }}
          git push origin ${{ steps.time.outputs.time }}

      - name: Send dingtalk message
        uses: ghostoy/dingtalk-action@master
        with:
          webhook: ${{ secrets.DINGTALK_WEBHOOK }}
          msgtype: actionCard
          content: |
            {
              "title": "自动部署成功",
              "btnOrientation": "1",
              "pc_slide": false,
              "btns": [
                {"title": "查看提交", "actionURL": "https://github.com/test-auto-deploy/source-code/commit/${{github.sha}}", "pc_slide": false},
                {"title": "查看版本", "actionURL": "https://github.com/test-auto-deploy/online-page/releases/tag/${{steps.time.outputs.time}}", "pc_slide": "false"},
                {"title": "线上地址", "actionURL": "dingtalk://dingtalkclient/page/link?url=https%3A%2F%2Ftest-auto-deploy.github.io%2Fonline-page%2F&pc_slide=false"}
              ],
              "text": "### 自动部署成功 \n ${{github.event.head_commit.message}}"
            }
